# NGP First Workflow
name: workflow2

on : push

jobs: 
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo "Hello from NGP"
          ls -l
          hostname
      - name: step2
        run: sleep 30
  job2:
    runs-on: unbuntu-latest
    steps:
      - name: step1 for copying the git
        uses: actions/checkout@v4.1.1
        name: step2
        run: echo "Hello again from NGP after setp2"
        
